# Generated by Django 4.1.6 on 2023-04-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AtUser',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='user',
            new_name='atuser',
        ),
    ]
