# Generated by Django 4.1.6 on 2023-04-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0002_rename_user_atuser_rename_user_loan_atuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan',
            new_name='LoanInstance',
        ),
    ]
